name: pca--noise-images-90k


dataset:
  annot_filename: dataset/noise_annots_90k.txt
  name: generator
  params:
    batch_size: 2048
    input_shape: [256, 256, 1]

model:
  name: pca
  params:
    n_components: 2000

# training:

  
  