name: unet--noise-images-90k


dataset:
  annot_filename: dataset/noise_annots_90k.txt
  name: generator
  params:
    batch_size: 16
    input_shape: [256, 256, 1]

model:
  name: unet
  params:
    filters: 64
    num_blocks: 4

training:
  epochs: 20
  
  optimizer:
    name: "adam"

  loss:
    name: "mse"

  metrics:
    - name: "mae"
      # params:
    
    - name: psnr
      # params:
  
  lr_scheduler:
    name: WarmupCosineSchedule
    params:
      base_lr: 0.1
      warmup_epochs: 4
      warmup_start_lr: 0.01
      max_epochs: 20
  
  
  